- src/api/ApiController.js
> fix: token 만료시 axios interceptor 로직 수정

- package-lock.json
- package.json
> chore: version up

- package-lock.json
- src/components/ErrorFrame.jsx
- src/pages/BadGateway.jsx
- src/pages/NotFound.jsx
- src/pages/SignUp.jsx
- src/styles/Common.jsx
NotFound, BadGateway 페이지 모듈화
components 폴더 - ErrorFrame 생성
Signup 페이지에서 가져다 쓰던 스타일 styles폴더에 common 스타일로 분리
> refac: 에러 페이지 모듈화

- package-lock.json
- package.json
- src/api/Auth.js
- src/components/BanFrame.jsx
- src/components/Etc/Button.jsx
- src/components/Etc/Wrapper.jsx
- src/components/Lecture/LectureContainer.jsx
- src/components/List/LectureList.jsx
- src/pages/BanReason.jsx
- src/pages/EmailSignUp.jsx
- src/pages/Exit.jsx
- src/pages/HistoryTest.jsx
- src/pages/IdSearch.jsx
- src/styles/Common.jsx
refactor: pages (1/3)
BadGateway, BanReason - ErrorFrame 생성
EmailSingUp - 중복 스타일 제거
Exit - react hook form 적용 및 중복 스타일 제거 (MUI 적용)
HistoryTest - props 간략화, 주석 제거
IdSearch - react hook form 적용 및 중복 스타일 제거 (MUI 적용)
* 추후 react hook form / react query 모듈화 필요
#9
> refactor: pages part 1

- src/api/Auth.js
- src/index.jsx
- src/pages/HistoryTest.jsx
- src/pages/LectureInfo.jsx
- src/pages/Login.jsx
- src/styles/Common.jsx
refactor: pages (2/3)
react 18 버전에 맞춰서 render 변경
input 최적화
appcontainer 공통 모듈 분리
login 페이지 최적화
> refactor: pages part 2 (1/2)

- src/api/Auth.js
- src/pages/Login.jsx
- src/pages/SignUp.jsx
- src/styles/Common.jsx
- src/utils/validate.js
react hook form 사용
form validation 로직 분리
- search 페이지 최적화 ...ing
> refactor: 회원가입 페이지 최적화

- src/components/List/MainList.jsx
- src/components/OptionSelect.jsx
- src/pages/Login.jsx
- src/pages/Main.jsx
- src/pages/Search.jsx
- src/pages/SignUp.jsx
- src/styles/Common.jsx
> refactor: search 페이지 최적화(메인,검색 필터선택 제작)

- src/components/Lecture/LectureCard.jsx
- src/components/List/EvaluationList.jsx
- src/components/List/MainList.jsx
- src/components/List/TestInfoList.jsx
- src/components/MajorSearch.jsx
- src/components/MajorSelect.jsx
- src/components/OptionSelect.jsx
- src/components/Write/WriteEvaluation.jsx
- src/components/Write/WriteTestInfo.jsx
- src/components/placeholderData.js
- src/pages/Main.jsx
- src/pages/Search.jsx
- src/styles/Common.jsx
- src/utils/subString.js
1. 강의 정렬 필터 사용성 증가
2. 모달 렌더링 오류 해결
> refactor: 모달 렌더링 오류 해결

- src/components/Lecture/IsTestInfo.jsx
- src/components/List/EvaluationList.jsx
- src/components/List/LectureList.jsx
- src/components/List/MainList.jsx
- src/components/List/SearchEvaluationList.jsx
- src/components/List/TestInfoList.jsx
- src/hooks/useLectureQuery.js
- src/hooks/useUserQuery.js
각각의 query들을 api 타입별로 모듈화 한다. (로직 분리)
> refactor: react-query 모듈화 진행

- src/components/Nav.jsx
- src/utils/loginStorage.js
const state = localStorage.login || sessionStorage.login;
> fix: 로그인 상태 버그 수정

- src/api/ApiController.js
- src/app/versionCheck.js
- src/components/EvaluationDetail.jsx
- src/components/Lecture/IsTestInfo.jsx
- src/components/Lecture/LectureCard.jsx
- src/components/Lecture/LectureDetail.jsx
- src/components/Lecture/LectureInfoBox.jsx
- src/components/List/EvaluationList.jsx
- src/components/List/MainList.jsx
- src/components/List/SearchEvaluationList.jsx
- src/components/List/SearchTestInfoList.jsx
- src/components/Major/MajorSearch.jsx
- src/hooks/useLectureQuery.js
- src/utils/floatFix.js
1. 전공선택 필터 로그인 상태 오류 수정
2. 로그인 미유지 로직 제거
3. toFixed 모듈화 작업(유틸)
4. react-query 모듈화 작업
> refactor: Lecture폴더 컴포넌트 최적화 작업

- src/api/ApiController.js
- src/api/Lecture.js
- src/api/Major.js
- src/api/Notice.js
- src/api/etc.js
- src/components/Major/MajorSearch.jsx
- src/hooks/useFavoriteMajor.js
- src/hooks/useSearch.js
1. API 리팩토링 추가작업
2. 전공선택 모달 뷰 & 로직 분리
> refactor: API 나머지 리팩토링 작업 및 전공선택 모달 커스텀 훅 생성

- src/api/ApiController.js
api 컨트롤러에서 리프레시 관련 에러 발견하여 수정합니다
> fix: 토큰 리프레시 관련 에러 수정

- src/api/User.js
- src/components/Lecture/LectureContainer.jsx
- src/components/List/SearchEvaluationList.jsx
- src/components/Major/MajorSearch.jsx
- src/components/UserInfo/UserInfo.jsx
- src/components/Write/WriteEvaluation.jsx
- src/components/Write/WriteTestInfo.jsx
- src/constants/placeholderData.js
- src/hooks/useFavoriteMajor.js
1. 각 컴포넌트 별 map 단순화
2. 강의평가/시험정보 작성 컴포넌트 select 데이터 반복문화
3. 전공선택 후 모달이 닫히지 않는 버그 수정
> refactor: 강의평가/시험정보 작성 컴포넌트 리팩토링 및 버그 수정

- src/components/Etc/RangeInput.jsx
- src/components/Footer.jsx
- src/components/UserInfo/UserInfo.jsx
- src/components/Write/WriteEvaluation.jsx
- src/components/Write/WriteTestInfo.jsx
- src/hooks/useFavoriteMajor.js
- src/hooks/useWriteEvaluation.js
1. 문의하기 링크 업데이트
2. 전공필터 모달 특정상황 안닫히는 버그 해결
3. 강의평가 작성 함수들 커스텀 훅으로 변경
> feat: 문의하기 메일 -> 링크 업데이트

- src/api/User.js
- src/components/Etc/RangeInput.jsx
- src/components/Footer.jsx
- src/components/Lecture/LectureContainer.jsx
- src/components/List/SearchEvaluationList.jsx
- src/components/Major/MajorSearch.jsx
- src/components/UserInfo/UserInfo.jsx
- src/components/Write/WriteEvaluation.jsx
- src/components/Write/WriteTestInfo.jsx
- src/constants/placeholderData.js
- src/hooks/useFavoriteMajor.js
- src/hooks/useWriteEvaluation.js
1. 강의평가 작성 컴포넌트 리팩토링
2. 전공필터 모달 닫히지 않는 버그 수정
3. 문의하기 URL 업데이트
> fix: 모달 닫히지 않는 버그 수정 및 문의하기 URL 업데이트

- src/hooks/useSearch.js
> refactor: useSearch

- src/api/ApiController.js
- src/components/Etc/Spinner.jsx
- src/pages/IdSearch.jsx
- src/pages/PwSearch.jsx
https://user-images.githubusercontent.com/83450991/233792167-752fb928-4b99-42df-b0e5-6baddaf2a9db.mp4
> fix: 아이디/비밀번호 찾기 중복 요청 방지 (버튼 disabled 처리)

- src/App.tsx
- src/components/Etc/ScrollButton.tsx
- src/components/Nav.tsx
`app.js`부분을 타입스크립트 마이그레이션 진행했어요
> refactor: typescript-app.js

- .github/workflows/ci-workflow.yml
- package.json
> feat: ci workflow

- .eslintrc.json
- package-lock.json
- src/components/Etc/ScrollButton.tsx
- src/components/MainBanner.tsx
- src/components/index.js
- src/pages/Main.tsx
- tsconfig.json
> refactor: main.js typescript

- src/api/User.ts
- src/hooks/useUserQuery.ts
- src/types/user.ts
> refactor: user api typescript

- src/api/User.ts
- src/components/UserInfo/UserAccount.tsx
- src/components/UserInfo/UserInfo.tsx
- src/components/UserInfo/UserPoint.tsx
- src/pages/MyInfo.tsx
- src/types/user.ts
> refactor: userinfo component typescript

- src/api/Lecture.ts
- src/components/Lecture/IsTestInfo.tsx
- src/types/exam.ts
> refactor: exam test typescript

- src/api/Lecture.ts
- src/components/List/MainList.tsx
- src/hooks/useLectureQuery.js
- src/types/lecture.ts
> refactor: main lecture list type

- package-lock.json
- package.json
- src/components/AsyncBoundary.tsx
> feat: AsyncBoundary

- src/api/User.ts
- src/pages/MyInfo.tsx
> fix: myinfo type error

- src/api/Lecture.ts
- src/components/OptionSelect.tsx
- src/pages/Main.tsx
- src/pages/Search.tsx
구조 변경했습니다.
외부에서 state를 주는 방식 -> 내부로 캡슐화, 불필요한 prop 값 3개 제거
> refactor: option select component

- src/api/Auth.ts
- src/pages/SignUp.tsx
- src/types/user.ts
- src/utils/validate.ts
> refactor: signup typescript

- src/index.tsx
- src/pages/Search.tsx
> feat: suspense, error boundary 적용

- src/api/Lecture.ts
- src/components/Lecture/LectureContainer.tsx
- src/components/Lecture/LectureInfoBox.tsx
- src/constants/placeholderData.ts
- src/types/lecture.ts
> r:efactor: lecture typescript etc

- package-lock.json
- package.json
- src/api/Lecture.ts
- src/components/Lecture/LectureCard.tsx
- src/components/Lecture/LectureContainer.tsx
- src/components/Lecture/LectureInfoBox.tsx
- src/constants/placeholderData.ts
- src/types/lecture.ts
> refactor: lecturecard and lecturetype

- src/components/EvaluationDetail.tsx
- src/components/Lecture/LectureInfoBox.tsx
- src/types/common.ts
- src/types/evaluate.ts
> refactor: evaluate typescript detail page

- src/api/User.ts
- src/pages/HistoryTest.tsx
- src/types/user.ts
> refactor: historytest page typescript

- src/components/Lecture/LectureDetail.tsx
- src/components/Lecture/LectureInfoBox.tsx
- src/pages/NoticeDetail.tsx
> refactor: lecture components && noticedetail page typescript

- src/api/User.ts
- src/components/List/EvaluationList.tsx
- src/types/evaluate.ts
> refactor: evaluationlist typescript

- src/components/List/SearchTestInfoList.tsx
- src/constants/placeholderData.ts
- src/types/exam.ts
> refactor: searchtest typescript component

- src/api/User.ts
- src/components/List/SearchTestInfoList.tsx
- src/components/List/TestInfoList.tsx
- src/types/evaluate.ts
- src/types/exam.ts
> refactor: testinfolist-typescript

- src/api/etc.ts
- src/components/Major/MajorSelect.tsx
- src/hooks/useFavoriteMajor.ts
> refactor: useFavoriteMajor-typescript

- src/components/Major/MajorSearch.tsx
- src/components/Write/WriteEvaluation.tsx
- src/hooks/useWriteEvaluation.ts
> refactor: writeevaluation-majorsearch-typescript

- src/api/Lecture.ts
- src/components/List/SearchEvaluationList.tsx
- src/constants/placeholderData.ts
- src/types/evaluate.ts
> refactor: searchevaluationlist-typescript

- src/app/recoilStore.ts
- src/components/Write/WriteTestInfo.tsx
- src/hooks/useLectureQuery.ts
- src/pages/LectureInfo.tsx
> refactor: typescript-all

- src/api/Auth.ts
- src/pages/Login.tsx
1. navigate 사용부 함수화
2. 기존 useRef로 값 전달하던 것들 useForm 사용하여 값 전달
3. axios error타입 단언하여(스웨거 api 에러 타입 참조) 에러 시 메시지 호출 
4. form submitting 시에 로그인 버튼 disabled 처리 (button opacity 조절)
점진적으로 개선해볼 예정입니다~
> refactor: 로그인 페이지 및 api 리팩토링
